### ISSUE TITLE
Demo and some clarifications

### ISSUE THREAD

**Issue by FranciZ** [thatisuday/ngx-image-gallery#15]
Hi,

This looks really promising, but I'm a little confused about the demo.

I guess the demo is not the same as the one deployed [here](https://thatisuday.github.io/ngx-image-gallery)?

It's not clear how you get reference to `this.ngxImageGallery` and all the commands are commented out. I can guess it's a `ViewChild` but those are important details that would be well to put in the demo.

It's also not clear how to use this in any kind of complex multi view or nested route setup since it's a component that needs placing in the root component and direct referencing to work. How would one go about reusing this across the webapp for displaying a gallery regardless from which component I want to do that. It's not a problem for me to setup a service that holds a reference to the component from root but some kind of a provider would be nice to handle these very common scenarios.

Very promising as I said but these either require some explanation in the demo or a general discussion.

Thanks!

**Comment by thatisuday** [comment]
Sure. I will do that soon. Give me few hours.

**Comment by AnthonyNahas** [comment]
@FranciZ here is an example on how u get reference to the `ngxImageGallery ` -->

### Example:

```html
<ngx-image-gallery #someVar
                   [images]="images2"
                   [conf]="conf2"
                   (onOpen)="galleryOpened($event)"
                   (onClose)="galleryClosed()"
                   (onImageChange)="galleryImageChanged($event)"
                   (onDelete)="deleteImage($event)">
</ngx-image-gallery>
```

via #someVar u can get access to the `NgxImageGalleryComponent`

-->

```ts
@ViewChild('someVar') ngxImageGallery: NgxImageGalleryComponent;
```

-->

now you can use the component and call the functions like the following -->

```ts
// next image in gallery
  nextImage() {
      this.ngxImageGallery.next();
  }
```

@FranciZ and @thatisuday I will write a major update in near future and this will include:

- a better documentation to the module
- an extended example
- combing two component of `NgxImageGalleryComponent` (that's why these methods are still commented and discard...)
- a nice UI with [Material Design](https://material.angular.io/)

**Comment by AnthonyNahas** [comment]
#16

**Comment by AnthonyNahas** [comment]
@FranciZ clone the repo and follow the steps to serve the demo app.
Another update will follow the next weeks..
If you have any questions pls do not hesitate. 

Thank you
